Algoritmo "SomaParametrosReferencia"
Var
// Seção de Declarações das variáveis 
   X,Y: inteiro
Procedimento Soma (Var A, B: Inteiro)
inicio
      A <- A + 1
      B <- B + 2
      escreval ("Valor de A = ", A)
      escreval ("Valor de B = ", B)
      escreval ("Soma de A + B = ", A+B)
FimProcedimento
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   X <- 4
   Y <- 8
   Soma (X, Y)
   escreval ("Valor de X = ", X)
   escreval ("Valor de Y = ", Y)

Fimalgoritmo